{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omni-cd.fullname" . }}
  labels:
    {{- include "omni-cd.labels" . | nindent 4 }}
type: Opaque
stringData:
  OMNI_ENDPOINT: {{ .Values.config.omni.endpoint | quote }}
  OMNI_SERVICE_ACCOUNT_KEY: {{ .Values.config.omni.serviceAccountKey | quote }}
  ADMIN_PASSWORD: {{ .Values.config.adminPassword | quote }}
  {{- if .Values.config.webhookSecret }}
  WEBHOOK_SECRET: {{ .Values.config.webhookSecret | quote }}
  {{- end }}
  {{- if .Values.config.oidc.enabled }}
  OIDC_CLIENT_SECRET: {{ .Values.config.oidc.clientSecret | quote }}
  {{- end }}
{{- end }}
